api_branch: origin/master
api_parser: ~
api_cfgmod: clone
api_runner: ~
api_paths: src
env_make: ~
env_prep: get-composer
env_post: ci-coveralls,ci-codacy
php_conf: timezone
php_exts: ~
app_prep: dep-composer,db-create,db-load
app_post: ~
app_path: bin/console
pkg_name: rf-app
pkg_desc: "The core Symfony-based web application powering the robfrawley.com domain."
pkg_bndl: false
