api_branch: origin/master
api_parser: ~
api_cfgmod: clone
api_runner: ~
api_paths: src
env_make: ~
env_prep: composer-get
php_conf: timezone
php_exts: ~
app_prep: symfony-cp-params,composer-req,symfony-db-make,symfony-db-load,symfony-assets-install,yarn-req,yarn-run-build
app_post: symfony-db-down
env_post: composer-del,ci-coveralls,ci-codacy
app_path: bin/console
pkg_name: rf-app
pkg_desc: "The core Symfony-based web application powering the robfrawley.com domain."
pkg_bndl: false
