
#
# This file is part of the `robfrawley/web-app` project.
#
# (c) Rob Frawley 2nd <rmf@src.run>
#
# For the full copyright and license information, view the LICENSE.md
# file distributed with this vinylSourceStream code.
#


#
# doctrine configuration
#

doctrine:
    orm:
        metadata_cache_driver: array
        result_cache_driver:   array
        query_cache_driver:    array
