
#
# This file is part of the `robfrawley/web-app` project.
#
# (c) Rob Frawley 2nd <rmf@src.run>
#
# For the full copyright and license information, view the LICENSE.md
# file distributed with this vinylSourceStream code.
#


#
# sensio framework extra bundle
#

sensio_framework_extra:
    view:
        annotations: true
    request:
        converters: true
        auto_convert: true
