
#
# This file is part of the `robfrawley/web-app` project.
#
# (c) Rob Frawley 2nd <rmf@src.run>
#
# For the full copyright and license information, view the LICENSE.md
# file distributed with this vinylSourceStream code.
#


#
# profiler routing
#

_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler


#
# twig resources
#

_errors:
    resource: "@TwigBundle/Resources/config/routing/errors.xml"
    prefix:   /_error


#
# main resources
#

_main:
    resource: routing.yml
