Rf\AppBundle\Doctrine\Entity\Email:

    type: entity
    table: sys_email_spool

    options:
        row_format: COMPRESSED
        charset: utf8mb4
        collate: utf8mb4_unicode_ci

    repositoryClass: Rf\AppBundle\Doctrine\Repository\EmailRepository

    id:

        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
            options:
                unsigned: true

    fields:

        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create

        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update

        status:
            type: string
            length: 2
            nullable: true

        environment:
            type: string
            length: 8
            nullable: true

        message:
            type: text
