Rf\AppBundle\Doctrine\Entity\Email:

    type: entity
    table: null

    options:
        row_format: DYNAMIC
        charset: utf8mb4
        collate: utf8mb4_unicode_ci

    repositoryClass: Rf\AppBundle\Doctrine\Repository\EmailRepository

    id:

        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:

        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create

        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update

        status:
            type: string
            length: 2

        environment:
            type: string
            length: 8

        message:
            type: text
