Rf\AppBundle\Doctrine\Entity\RevisionLog:

    type: entity
    table: sys_revision_logs

    options:
        row_format: DYNAMIC
        charset: utf8mb4
        collate: utf8mb4_unicode_ci

    repositoryClass: Rf\AppBundle\Doctrine\Repository\RevisionLogRepository

    id:

        uuid:
            type: string
            length: 36
            id: true
            generator:
                strategy: CUSTOM
            customIdGenerator:
                class: SR\Doctrine\ORM\Id\StringUuid4PessimisticGenerator

    fields:

        action:
            type: string
            length: 8

        created:
            type: datetime
            gedmo:
                timestampable:
                    on: update

        objectId:
            type: string
            length: 64
            nullable: true

        objectClass:
            type: string
            length: 255

        version:
            type: integer
            options:
                unsigned: true

        data:
            type: array
            nullable: true

        username:
            type: string
            length: 255
            nullable: true

    indexes:

        revision_class_idx:
            columns:
                - object_class

        revision_date_idx:
            columns:
                - created

        revision_user_idx:
            columns:
                - username

        revision_version_idx:
            columns:
                - object_id
                - object_class
                - username
