Rf\AppBundle\Doctrine\Entity\SearchIndexLog:

    type: entity
    table: sys_search_index_logs

    options:
        row_format: COMPRESSED
        charset: utf8mb4
        collate: utf8mb4_unicode_ci

    repositoryClass: Rf\AppBundle\Doctrine\Repository\SearchIndexLogRepository

    id:

        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
            options:
                unsigned: true

    fields:

        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update

        success:
            type: boolean

        objectIdentity:
            type: string
            length: 64

        objectClass:
            type: string
            length: 384

        objectHash:
            type: string
            length: 128
            nullable: true

    uniqueConstraints:

        stem_position_object_uniq:
            columns:
                - object_identity
                - object_class
    indexes:

        identity_class_hash_idx:
            columns:
                - object_identity
                - object_class
                - object_hash
