Rf\AppBundle\Doctrine\Entity\SearchIndex:

    type: entity
    table: sys_search_index_maps

    options:
        row_format: COMPRESSED
        charset: utf8mb4
        collate: utf8mb4_unicode_ci

    repositoryClass: Rf\AppBundle\Doctrine\Repository\SearchIndexRepository

    id:

        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
            options:
                unsigned: true

    fields:

        position:
            type: bigint
            options:
                unsigned: true

        objectIdentity:
            type: string
            length: 64

        objectClass:
            type: string
            length: 384

    manyToOne:

        stem:
            targetEntity: Rf\AppBundle\Doctrine\Entity\SearchStem
            joinColumn:
                name: stem_id
                referencedColumnName: id
            inversedBy: indices

    uniqueConstraints:

        object_stem_position_uniq:
            columns:
                - object_class
                - object_identity
                - stem_id
                - position
